(()=>{
 const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};let variants;
 try{variants=JSON.parse(localStorage.getItem('zt-cart-options')||'{}')}catch{variants={}}
 const checkout=document.querySelector('#checkout-items'),productName=document.querySelector('#occasion-product-name');if(!checkout&&!productName)return;
 const save=()=>localStorage.setItem('zt-cart-options',JSON.stringify(variants));
 fetch('/api/atelier/catalog').then(r=>r.json()).then(products=>{
 function options(p){const wrap=make('div');wrap.className='cart-options';const sizes=make('select');sizes.setAttribute('aria-label',p.name+' size');const blank=make('option','Select size');blank.value='';sizes.append(blank);(p.sizes||[]).forEach(size=>{const option=make('option',size);option.value=size;sizes.append(option)});sizes.value=variants[p.id]?.size||'';const quantity=make('input');quantity.type='number';quantity.min=1;quantity.max=5;quantity.value=variants[p.id]?.quantity||1;quantity.setAttribute('aria-label',p.name+' quantity');function update(){variants[p.id]={size:sizes.value,quantity:Math.min(5,Math.max(1,Number(quantity.value)||1))};save();total()}sizes.onchange=update;quantity.onchange=update;wrap.append(sizes,quantity);return wrap}
 function total(){if(!checkout)return;let sum=0;checkout.querySelectorAll('.checkout-item h2').forEach(n=>{const p=products.find(p=>p.name===n.textContent);if(p)sum+=p.price*(variants[p.id]?.quantity||1)});const subtotal=document.querySelector('#cart-subtotal');if(subtotal)subtotal.textContent='Dress subtotal: $'+sum.toLocaleString('en-US')}
 if(productName){const id=new URLSearchParams(location.search).get('dress'),p=products.find(p=>p.id===(id==='red-occasion-dress'?'red-evening-gown':id));if(p){document.querySelector('#occasion-add').before(options(p));const info=make('p',p.production||'Sizing and availability are confirmed by the atelier.');document.querySelector('#occasion-add').before(info)}}
 if(!checkout)return;const summary=document.querySelector('#checkout-summary');const pay=make('button','Proceed to secure payment');pay.type='button';pay.className='button burgundy';pay.hidden=true;const status=make('p');status.setAttribute('role','status');summary.append(pay,status);
 function renderOptions(){checkout.querySelectorAll('.checkout-item').forEach(row=>{if(row.querySelector('.cart-options'))return;const p=products.find(p=>p.name===row.querySelector('h2')?.textContent);if(p)row.querySelector('div').append(options(p))});total()}
 new MutationObserver(renderOptions).observe(checkout,{childList:true});renderOptions();
 fetch('/api/payments/config').then(r=>r.json()).then(config=>{pay.hidden=!config.enabled;if(config.enabled){summary.querySelector('h2').textContent='Secure checkout';summary.querySelector('h2+p').textContent='Select size and quantity. Delivery and tax are calculated at checkout.'}}).catch(()=>{});
 pay.onclick=async()=>{pay.disabled=true;try{const items=[...checkout.querySelectorAll('.checkout-item h2')].map(n=>{const p=products.find(p=>p.name===n.textContent);return {id:p.id,size:variants[p.id]?.size||'',quantity:variants[p.id]?.quantity||1}});const response=await fetch('/api/payments/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});const result=await response.json();if(!response.ok)throw new Error(result.error);location.href=result.url}catch(error){status.textContent=error.message;pay.disabled=false}};
 const params=new URLSearchParams(location.search);if(params.has('order'))fetch('/api/payments/order?id='+encodeURIComponent(params.get('order'))+'&token='+encodeURIComponent(params.get('token')||'')).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);status.textContent='Order '+data.reference+' · '+(data.status==='paid'?'Payment confirmed.':'Awaiting payment confirmation.');summary.hidden=false;history.replaceState(null,'','checkout.html')}).catch(error=>status.textContent=error.message);
 }).catch(()=>{});
})();
