import SCHEMA from './measurement-schema.js';
const $=s=>document.querySelector(s);let mode='login',client,view='overview',month=new Date();month.setDate(1);
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
async function api(route,method='GET',data){const res=await fetch('/api/client/'+route,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});let value;try{value=await res.json()}catch{throw new Error('The account server is unavailable. Open this site through the Zateemee server.')}if(!res.ok)throw Object.assign(new Error(value.error||'Please try again.'),{status:res.status});return value}
function authMode(next){mode=next;$('#name-label').hidden=mode==='login';$('#name-label input').required=mode==='register';$('#auth-title').textContent=mode==='login'?'Welcome back.':'Your journey starts here.';$('#auth-submit').textContent=mode==='login'?'Sign in →':'Create account →';$('#signin-tab').setAttribute('aria-pressed',mode==='login');$('#register-tab').setAttribute('aria-pressed',mode==='register');$('[name=password]').autocomplete=mode==='login'?'current-password':'new-password';$('#auth-message').textContent=''}
$('#signin-tab').onclick=()=>authMode('login');$('#register-tab').onclick=()=>authMode('register');
$('#auth-form').onsubmit=async e=>{e.preventDefault();const button=$('#auth-submit');button.disabled=true;$('#auth-message').textContent='';try{await api(mode,'POST',Object.fromEntries(new FormData(e.target)));e.target.reset();await load()}catch(err){$('#auth-message').textContent=err.message}finally{button.disabled=false}};
async function load(){client=await api('me');$('#auth').hidden=true;$('#portal').hidden=false;document.body.classList.add('authenticated');$('#client-name').textContent=client.name;render()}
$('#logout').onclick=async()=>{try{await api('logout','POST',{});client=null;$('#portal').hidden=true;$('#auth').hidden=false;document.body.classList.remove('authenticated');authMode('login')}catch(err){$('#portal-message').textContent=err.message}};
const labels={overview:['YOUR COUTURE JOURNEY','A little closer to forever.','Your appointments, measurements and atelier updates, thoughtfully brought together.'],measurements:['01 / THE PERFECT FIT','Made around you.','Keep your fit details in one place. The atelier should verify these measurements before cutting your garment.'],calendar:['02 / YOUR CALENDAR','Make room for your moment.','Your requested appointments appear here. Dates and times remain subject to atelier confirmation.'],booking:['03 / APPOINTMENTS','Let’s meet at the atelier.','Request a consultation or fitting. Your chosen time is a preference, not a confirmed booking.'],production:['04 / PRODUCTION HUB','The making of your moment.','Follow your garment’s journey through the atelier once your order is connected.']};
function go(next){view=labels[next]?next:'overview';history.replaceState(null,'','#'+view);render()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));
function appointments(){return [...client.appointments].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))}
function appointmentList(){return appointments().map(a=>`<div class="appointment"><div><p><strong>${escape(a.type)}</strong></p><p>${escape(a.date)} · ${escape(a.time)} · Atelier local time</p></div><span class="badge">${escape(a.status)}</span></div>`).join('')||'<p class="muted">No appointment requests yet.</p>'}
function render(){document.body.dataset.view=view;const artwork={overview:['selena-seated','Every detail. Entirely yours.'],measurements:['esther-detail','The art of a perfect fit.'],booking:['selena-front','A conversation worth dressing for.'],calendar:['atelier-details','Your next chapter, beautifully planned.'],production:['atelier-lace','Crafted with care. Made for you.']}[view];$('#module-art').innerHTML=`<img src="assets/${artwork[0]}.webp" alt=""><div><span>ZATEEMEE / THE PRIVATE ATELIER</span><p>${artwork[1]}</p></div>`;const [label,title,description]=labels[view];$('#view-label').textContent=label;$('#view-title').textContent=title;$('#view-description').textContent=description;$('#portal-message').textContent='';document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});const content=$('#view-content');
 if(view==='overview'){const fields=Object.values(client.measurements.values||{}).filter(Boolean).length;content.innerHTML=`<div class="summary-strip"><span>Welcome, ${escape(client.name)}.</span><span>${fields}/64 fit details · ${client.appointments.length} appointment requests</span></div><div class="cards">${[['measurements','01','Measurements','A silhouette shaped around your own proportions.',fields?'Review your fit details':'Add your measurements'],['calendar','02','My calendar','Your consultations and fittings, all in view.','Open my calendar'],['booking','03','Appointments','Begin a conversation with the atelier.','Request an appointment'],['production','04','Production hub','Every considered step, from consultation to delivery.','View my journey']].map(([id,n,title,desc,cta])=>`<a class="module-card" href="#${id}" data-go="${id}"><span class="number">${n} / YOUR ATELIER</span><h2>${title}</h2><p>${desc}</p><b>${cta} ↗</b></a>`).join('')}</div>`;content.querySelectorAll('[data-go]').forEach(a=>a.onclick=e=>{e.preventDefault();go(a.dataset.go)})}
 if(view==='measurements'){const m=client.measurements;content.innerHTML=`<div class="fit-progress"><span>Your fit profile</span><strong>${Object.values(m.values||{}).filter(Boolean).length}<small> / 64 details</small></strong><div class="progress-track"><i style="width:${Object.values(m.values||{}).filter(Boolean).length/64*100}%"></i></div></div><div class="note">Use a soft measuring tape, keep it level, and choose one unit throughout. Leave unfamiliar fields blank for the atelier. ${m.updatedAt?'Last saved: '+escape(new Date(m.updatedAt).toLocaleString()):''}</div><form id="measurement-form"><div class="form-grid"><label>Measurement unit<select name="unit"><option value="inches">Inches</option><option value="cm">Centimetres</option></select></label><label>Garment / style<input name="garment" maxlength="150" value="${escape(m.garment)}" placeholder="Your chosen silhouette"></label></div>${SCHEMA.map((group,i)=>`<details class="measurement-section" ${i===0?'open':''}><summary>${escape(group.title)} · ${group.items.length} fit points</summary><div class="form-grid">${group.items.map(([id,label])=>`<label>${id}. ${escape(label)}<input name="m${id}" maxlength="40" value="${escape(m.values?.[id])}" placeholder="Leave blank if unknown"></label>`).join('')}</div></details>`).join('')}<label>Fit notes<textarea name="notes" maxlength="2000" placeholder="Tell us anything the atelier should know">${escape(m.notes)}</textarea></label><button class="primary">Save my measurements →</button></form>`;content.querySelector('[name=unit]').value=m.unit||'inches';$('#measurement-form').onsubmit=e=>save(e,'measurements','PUT',data=>({unit:data.get('unit'),garment:data.get('garment'),notes:data.get('notes'),values:Object.fromEntries(SCHEMA.flatMap(g=>g.items).map(([id])=>[id,data.get('m'+id)]))}),'Your measurements have been saved.')}
 if(view==='booking'){content.innerHTML=`<div class="note">No payment is collected here. The atelier will need to confirm availability, location and any consultation fee. Requests are saved in your account; email notifications are not connected yet.</div><form id="booking-form" class="panel"><div class="booking-heading"><span class="section-number">01</span><div><h2>Your appointment, your way.</h2><p>Choose a conversation. Share your vision.</p></div></div><div class="appointment-choices">${['Bridal consultation','Bespoke couture','Fitting'].map((t,i)=>`<button type="button" data-appointment="${t}" aria-pressed="${i===0}"><span>0${i+1}</span>${t}</button>`).join('')}</div><div class="form-grid"><label>Appointment type<select name="type"><option>Bridal consultation</option><option>Bespoke couture</option><option>Fitting</option></select></label><label>Preferred date<input type="date" name="date" min="${dateKey(new Date())}" required></label><label>Preferred time<select name="time">${[9,10,11,12,13,14,15].map(h=>`<option value="${String(h).padStart(2,'0')}:00">${String(h).padStart(2,'0')}:00</option>`).join('')}</select></label><label>Time reference<input value="Atelier local time — confirm with the atelier" readonly></label><label class="wide">Your vision<textarea name="notes" maxlength="2000" placeholder="Your occasion, preferred gown, and anything you would like to discuss"></textarea></label></div><button class="primary">Request appointment →</button></form><h2>Your requests</h2>${appointmentList()}`;content.querySelectorAll('[data-appointment]').forEach(b=>b.onclick=()=>{content.querySelector('[name=type]').value=b.dataset.appointment;content.querySelectorAll('[data-appointment]').forEach(c=>c.setAttribute('aria-pressed',c===b))});content.querySelector('[name=type]').onchange=e=>content.querySelectorAll('[data-appointment]').forEach(c=>c.setAttribute('aria-pressed',c.dataset.appointment===e.target.value));$('#booking-form').onsubmit=e=>save(e,'appointments','POST',data=>Object.fromEntries(data),'Your request is saved and appears in your calendar. It is awaiting atelier confirmation.')}
 if(view==='calendar')renderCalendar();
 if(view==='production'){const order=client.production;if(!order){content.innerHTML='<div class="empty"><p class="eyebrow">YOUR JOURNEY IS YET TO BEGIN</p><h2>Something beautiful takes shape.</h2><p>No production order is linked to this account yet. Once the atelier connects your order, your confirmed milestones will appear here.</p><a href="contact.html">Contact the atelier about your order ↗</a></div>';return}const stages=['Client Onboarding','Dress Consultation','Toile Fitting','Final Fitting','Packaging','Delivery'];content.innerHTML=`<div class="panel"><h2>${escape(order.garment||'Your couture garment')}</h2><ol class="timeline">${stages.map(s=>`<li>${s}<span>${escape(order.milestones?.[s]||'Awaiting update')}</span></li>`).join('')}</ol></div>`}
}
async function save(e,route,method,transform,message){e.preventDefault();const button=e.target.querySelector('button.primary');button.disabled=true;try{await api(route,method,transform(new FormData(e.target)));await load();$('#portal-message').textContent=message;$('#portal-message').scrollIntoView({block:'nearest'})}catch(err){$('#portal-message').textContent=err.message;if(err.status===401){$('#portal').hidden=true;$('#auth').hidden=false;$('#auth-message').textContent='Your session expired. Please sign in again.'}}finally{button.disabled=false}}
function renderCalendar(){const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),offset=(month.getDay()+6)%7;$('#view-content').innerHTML=`<div class="panel"><div class="month-controls"><button id="prev-month" aria-label="Previous month">‹</button><h2>${month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button id="next-month" aria-label="Next month">›</button></div><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="weekday">${d}</div>`).join('')}${Array.from({length:offset},()=>'<div></div>').join('')}${Array.from({length:days},(_,i)=>{const date=dateKey(new Date(month.getFullYear(),month.getMonth(),i+1));return `<div class="${date===dateKey(new Date())?'today':''}">${i+1}${appointments().filter(a=>a.date===date).map(a=>`<small>${escape(a.time)} ${escape(a.type)} · ${escape(a.status)}</small>`).join('')}</div>`}).join('')}</div></div><h2>All appointment requests</h2>${appointmentList()}`;$('#prev-month').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$('#next-month').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()}}
view=labels[location.hash.slice(1)]?location.hash.slice(1):'overview';$('#year').textContent=new Date().getFullYear();load().catch(err=>{if(err.status!==401)$('#auth-message').textContent=err.message});
