(() => {
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const pictures=document.querySelectorAll('.house-story .story-photo,.designer-rack-photo,.asa-photos button,.forever-photo-grid button,.occasion-photo,.home-editorials .story-photo');
 if(!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('photo-arrived');observer.unobserve(entry.target)}}),{threshold:.08});pictures.forEach(photo=>{photo.classList.add('photo-reveal');observer.observe(photo)});reduced.addEventListener('change',()=>{if(reduced.matches){observer.disconnect();pictures.forEach(photo=>photo.classList.add('photo-arrived'))}})}
 const nav=document.querySelector('#navigation'),menu=document.querySelector('.menu-toggle');if(!nav||!menu)return;
 const logo=document.createElement('a');logo.className='mobile-menu-brand';logo.href='index.html';logo.setAttribute('aria-label','Zateemee home');logo.innerHTML='<img src="assets/zateemee-logo.png" alt="Zateemee Bride" width="200" height="87">';nav.prepend(logo);
 const media=matchMedia('(max-width: 760px)');function sync(){document.body.classList.toggle('mobile-menu-open',media.matches&&menu.getAttribute('aria-expanded')==='true')}
 new MutationObserver(sync).observe(menu,{attributes:true,attributeFilter:['aria-expanded']});media.addEventListener('change',sync);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&media.matches&&menu.getAttribute('aria-expanded')==='true'){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');menu.focus()}});
 nav.addEventListener('click',e=>{if(e.target.closest('a')&&media.matches){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}});
 const collections=[...nav.querySelectorAll('.nav-dropdown')].find(dropdown=>dropdown.querySelector('summary')?.textContent.trim()==='Collections');if(collections){const panel=collections.querySelector('.dropdown-panel');const line=document.createElement('span');line.className='collection-nav-line';panel.append(line);function position(link){line.style.top=link.offsetTop+link.offsetHeight-5+'px';line.style.width=Math.max(0,link.offsetWidth-40)+'px';line.style.opacity='1'};panel.querySelectorAll('a').forEach(link=>{link.addEventListener('pointerenter',()=>position(link));link.addEventListener('focus',()=>position(link))});panel.addEventListener('pointerleave',()=>line.style.opacity='0')}
})();

(() => {
 const page=location.pathname.split('/').pop()||'index.html';
 document.querySelectorAll('#navigation a').forEach(a=>{if(new URL(a.href).pathname.split('/').pop()===page){a.setAttribute('aria-current','page');a.closest('details')?.classList.add('nav-current')}});
 const heading=document.querySelector('.dress-heading');if(heading){const crumb=document.createElement('nav');crumb.className='page-breadcrumb';crumb.setAttribute('aria-label','Breadcrumb');crumb.innerHTML='<a href="index.html">Home</a><span>/</span><a href="wedding-dresses.html">Wedding Dresses</a>';heading.prepend(crumb);const description=heading.querySelector('.gown-description');if(description){const details=document.createElement('details');details.className='gown-details';details.open=true;const summary=document.createElement('summary');summary.textContent='Design details';description.before(details);details.append(summary,description)}}
 if(page==='contact.html'){const section=document.querySelector('#contact');const choices=document.createElement('div');choices.className='enquiry-choices';choices.setAttribute('aria-label','Choose your enquiry');[['Bridal','bespoke'],['Special Occasions','special'],['Wholesale','wholesale']].forEach(([label,value])=>{const a=document.createElement('a');a.textContent=label;a.href='contact.html?interest='+value;choices.append(a)});section?.querySelector('form')?.before(choices);if(new URLSearchParams(location.search).get('interest')==='special'){const select=document.querySelector('[name=interest]');if(select)select.value='Special event'}}
 if(page==='blog.html'){const empty=document.querySelector('.blog-empty');if(empty){const frame=document.createElement('div');frame.className='journal-feature';frame.innerHTML='<img src="assets/story-gallery/story-01.webp" alt="Zateemee bridal house" width="2200" height="2750"><div><p class="eyebrow">ZATEEMEE JOURNAL</p></div>';empty.before(frame);frame.querySelector('div').append(empty)}}
 const existing=document.querySelector('#cart-dialog');if(existing)existing.classList.add('cart-drawer');
})();
(() => {
 const cartButton=document.querySelector('[data-tool=cart]');if(!cartButton)return;let drawer=document.querySelector('#cart-dialog');if(!drawer){drawer=document.createElement('dialog');drawer.id='cart-dialog';document.body.append(drawer)}drawer.classList.add('cart-drawer');drawer.setAttribute('aria-label','Your Special Occasions cart');
 function read(){try{const value=JSON.parse(localStorage.getItem('zateemee-bag')||'[]');return Array.isArray(value)?value:[]}catch{return []}}
 function render(){drawer.replaceChildren();const close=document.createElement('button');close.className='close';close.type='button';close.textContent='×';close.setAttribute('aria-label','Close cart');close.addEventListener('click',()=>drawer.close());const title=document.createElement('h2');title.textContent='Your cart';drawer.append(close,title);const products=(window.zateemeeOccasions||[]).filter(p=>read().includes(p.name));if(!products.length){const empty=document.createElement('p');empty.textContent='Your cart is empty. Explore Special Occasions dresses.';drawer.append(empty)}products.forEach(p=>{const row=document.createElement('div');row.className='bag-row';const image=document.createElement('img');image.src='assets/'+p.image+'.webp';image.alt=p.name;const name=document.createElement('span');name.textContent=p.name;const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+p.name);remove.addEventListener('click',()=>{localStorage.setItem('zateemee-bag',JSON.stringify(read().filter(n=>n!==p.name)));render()});row.append(image,name,remove);drawer.append(row)});const link=document.createElement('a');link.className='button burgundy';link.href=products.length?'checkout.html':'special-event.html';link.textContent=products.length?'Review cart & checkout':'Explore Special Occasions';drawer.append(link)}
 cartButton.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();render();drawer.showModal()},{capture:true});
})();
