import {moderatorAllowed,notificationQueue} from './community-moderation.mjs';
import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,readFileSync} from 'node:fs';
import path from 'node:path';
import {randomBytes} from 'node:crypto';
const directory=path.resolve(process.env.DATA_DIR||'data');mkdirSync(directory,{recursive:true});
const db=new DatabaseSync(path.join(directory,'community.sqlite'));
db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS reviews(id TEXT PRIMARY KEY,name TEXT NOT NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),text TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created TEXT NOT NULL);CREATE TABLE IF NOT EXISTS comments(id TEXT PRIMARY KEY,post TEXT NOT NULL,name TEXT NOT NULL,text TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created TEXT NOT NULL);CREATE TABLE IF NOT EXISTS reactions(post TEXT NOT NULL,visitor TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('like','love')),PRIMARY KEY(post,visitor,kind));`);
const notifications=notificationQueue(db);const limits=new Map();const reject=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
function posts(){try{return JSON.parse(readFileSync(process.env.POSTS_FILE||new URL('../content/posts.json',import.meta.url),'utf8').replace(/^\uFEFF/,''))}catch{return []}}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>12000)reject('Request too large',413)}try{return JSON.parse(raw)}catch{reject('Invalid request')}}
function text(value,max){if(typeof value!=='string'||!value.trim()||value.length>max)reject('Please complete all fields within the character limit.');return value.trim()}
export async function communityApi(req,res){if(!req.url.startsWith('/api/community/'))return false;const send=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))};try{const url=new URL(req.url,'http://localhost'),route=url.pathname;
if(req.method!=='GET'){if(!req.headers.origin||new URL(req.headers.origin).host!==req.headers.host)reject('Request origin rejected',403);const key=req.socket.remoteAddress;let limit=limits.get(key);if(!limit||limit.until<Date.now())limit={count:0,until:Date.now()+900000};limits.set(key,limit);if(++limit.count>30)reject('Please try again later.',429)}
if(route==='/api/community/moderation'){if(!moderatorAllowed(req))reject('Moderator access required.',401);if(req.method==='GET'){send({entries:[...db.prepare("SELECT *, 'reviews' AS kind FROM reviews WHERE status='pending'").all(),...db.prepare("SELECT *, 'comments' AS kind FROM comments WHERE status='pending'").all()],notifications:notifications.status()});return true}if(req.method==='POST'){const data=await body(req);if(!['reviews','comments'].includes(data.kind)||!['publish','reject'].includes(data.action))reject('Invalid moderation action');const result=db.prepare(`UPDATE ${data.kind} SET status=? WHERE id=? AND status='pending'`).run(data.action==='publish'?'published':'rejected',data.id);if(!result.changes)reject('Pending submission not found',404);send({message:'Submission '+data.action});return true}reject('Method not allowed',405)}
if(route.endsWith('/reviews')&&req.method==='GET'){send(db.prepare("SELECT name,rating,text,created FROM reviews WHERE status='published' ORDER BY created DESC LIMIT 100").all());return true}
if(route.endsWith('/reviews')&&req.method==='POST'){const data=await body(req);if(!Number.isInteger(data.rating)||data.rating<1||data.rating>5)reject('Choose a rating from 1 to 5.');const id=randomBytes(16).toString('hex');const name=text(data.name,80),review=text(data.text,2000);db.exec('BEGIN');try{db.prepare('INSERT INTO reviews(id,name,rating,text,created) VALUES(?,?,?,?,?)').run(id,name,data.rating,review,new Date().toISOString());notifications.enqueue(id,'New Zateemee review awaiting approval',name+' · '+data.rating+'/5\n\n'+review+'\n\nOpen your private approval queue: '+(process.env.PUBLIC_SITE_URL||'http://127.0.0.1:4173')+'/moderation.html');db.exec('COMMIT')}catch(error){db.exec('ROLLBACK');throw error}send({message:'Thank you. Your review has been saved for approval.'},201);return true}
if(route.endsWith('/posts')&&req.method==='GET'){const list=posts();send(list.map(post=>({...post,reactions:db.prepare('SELECT kind,COUNT(*) AS count FROM reactions WHERE post=? GROUP BY kind').all(post.id)})));return true}
const post=url.searchParams.get('post');if(!posts().some(item=>item.id===post))reject('Article not found',404);
if(route.endsWith('/comments')&&req.method==='GET'){send(db.prepare("SELECT name,text,created FROM comments WHERE post=? AND status='published' ORDER BY created LIMIT 100").all(post));return true}
if(route.endsWith('/comments')&&req.method==='POST'){const data=await body(req);db.prepare('INSERT INTO comments(id,post,name,text,created) VALUES(?,?,?,?,?)').run(randomBytes(16).toString('hex'),post,text(data.name,80),text(data.text,2000),new Date().toISOString());send({message:'Your comment has been saved for approval.'},201);return true}
if(route.endsWith('/reactions')&&req.method==='POST'){const data=await body(req);if(!['like','love'].includes(data.kind))reject('Invalid reaction');let visitor=/zt_visitor=([a-f0-9]{32})(?:;|$)/.exec(req.headers.cookie||'')?.[1];if(!visitor){visitor=randomBytes(16).toString('hex');res.setHeader('Set-Cookie',`zt_visitor=${visitor}; HttpOnly; SameSite=Lax; Path=/; Max-Age=31536000${process.env.NODE_ENV==='production'?'; Secure':''}`)}const exists=db.prepare('SELECT 1 FROM reactions WHERE post=? AND visitor=? AND kind=?').get(post,visitor,data.kind);if(exists)db.prepare('DELETE FROM reactions WHERE post=? AND visitor=? AND kind=?').run(post,visitor,data.kind);else db.prepare('INSERT INTO reactions VALUES(?,?,?)').run(post,visitor,data.kind);send({active:!exists,count:db.prepare('SELECT COUNT(*) AS count FROM reactions WHERE post=? AND kind=?').get(post,data.kind).count});return true}
reject('Endpoint not found',404)
}catch(error){send({error:error.status?error.message:'Unable to save. Please try again.'},error.status||500)}return true}
